"""empty message

Revision ID: feee069ab8c1
Revises: 722a8cb73245
Create Date: 2020-02-07 15:50:31.765210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'feee069ab8c1'
down_revision = '722a8cb73245'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie_genre',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.genre_id'], ),
    sa.ForeignKeyConstraint(['title'], ['movie.title'], ),
    sa.PrimaryKeyConstraint('title', 'genre_id')
    )
    op.create_table('user_movie',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('user_rating', sa.Float(precision=10), nullable=True),
    sa.ForeignKeyConstraint(['title'], ['movie.title'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'title')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_movie')
    op.drop_table('movie_genre')
    # ### end Alembic commands ###
